---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      provider: fabric8
      project: hiker-santander-carga-registro-boleto-application
      version: 2.0.0-SNAPSHOT
      group: com.accesstage
    name: hiker-santander-carga-registro-boleto
  spec:
    ports:
    - nodePort: 30551
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      project: hiker-santander-carga-registro-boleto-application
      provider: fabric8
      group: com.accesstage
    type: NodePort
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      provider: fabric8
      project: hiker-santander-carga-registro-boleto-application
      version: 2.0.0-SNAPSHOT
      group: com.accesstage
    name: hiker-santander-carga-registro-boleto-application
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: hiker-santander-carga-registro-boleto-application
        provider: fabric8
        version: 2.0.0-SNAPSHOT
        group: com.accesstage
    template:
      metadata:
        labels:
          provider: fabric8
          project: hiker-santander-carga-registro-boleto-application
          version: 2.0.0-SNAPSHOT
          group: com.accesstage
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SPRING_PROFILES_ACTIVE
            value: develop
          image: registrydev.accesstage.com.br:5000/hiker-santander-carga-registro-boleto:2.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: hiker-santander-carga-registro-boleto
          securityContext:
            privileged: false
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
          volumeMounts:
          - mountPath: "/data"
            name: mypd
        volumes:
          - name: mypd
            persistentVolumeClaim:
              claimName: dev-nfs-claim
